import React from 'react';

const NotFound = () => (
  <main className="static" style={{ background: '#fff' }}>
    HELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO
    WORLD HELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO
    WORLDHELLO WORLD HELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO
    WORLDHELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO
    WORLDHELLO WORLDHELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLDHELLO WORLDHELLO
    WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLD HELLO WORLDHELLO WORLDHELLO
    WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLDHELLO WORLD
  </main>
);

export default NotFound;
